### ISSUE TITLE
error: "jack.h" not found

### ISSUE THREAD

**Issue by atchoo78** [ovenwerks/mcpdisp#2]
```zsh
~ $ make
c++ -Wall -pedantic -std=c++0x -I/usr/local/opt/qt/include  -c -o mcpdisp.o mcpdisp.cc
mcpdisp.cc:27:10: fatal error: 'jack/jack.h' file not found
#include <jack/jack.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [mcpdisp.o] Error 1
```
macOS 10.15.5

**Comment by ovenwerks** [comment]
I notice it says macOS on the bottom. I am not sure how you would install libjack, but wou8ld guess it is not installed. It also looks like someone has messed with the makefile because I am not sure where the -I/usr/local/opt/qt/include comes from as there is no qt code in here at all. The gui toolkit is fltk. Both jack and fltk need to be installed. In most linux instalations the approriate  -dev packages also need to be installed. In debian these are libjack-jackd2-dev and libfltk-dev or similar. These will as well as installing the include files, pull in the libs.

If you are truly trying to build this on macOS, I can't help you. You will probably have to install both jackd and fltk and maybe build them as well. which is beyond me.

**Comment by atchoo78** [comment]
Got it up and running on macOS Catalina. 

```bash

brew install jack, fltk, meson, ninja

meson build --prefix=/usr/local
cd build && ninja
sudo -H ninja install

```

Reboot/restart CoreAudio.

```bash

sudo -H ./jackd -d coreaudio -l -c 2 -P  

```
open another terminal window/shell 

```bash

sudo ./mcpdisp -m -t  

```
- faders go -*-.woosh.-*-
